### ISSUE TITLE
new cell v0.5 is reporting the wrong temperature

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/hardware#2]
The first v0.5 cell tested ([C509](http://relay.heatseeknyc.com/cells/0013a20040dc273e)) is reporting 111ºF in live mode from inside our improvised thermal chamber along with an extech air probe reporting 73ºF. 

![Heat Seek NYC Cell v0.5](https://cloud.githubusercontent.com/assets/4542879/11824128/e6e2d824-a345-11e5-95d4-8f3027bedf57.jpg)

**Comment by hrldcpr** [comment]
This is (hopefully) not a hardware issue, but something we should change in firmware and perhaps relay.

In particular, the formula here - https://github.com/heatseeknyc/firmware/blob/2dadd864efc0256e5e55427ce842b3f6e683f441/hub/receiver.py#L57 - only applies to the old temperature chip, so we need a place (probably the relay server) that knows which type of board is being used and then uses the correct formula.

thus, two new issues:
heatseeknyc/firmware#9
heatseeknyc/relay#11
