### ISSUE TITLE
add GERBER files or procedure for making them

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/hardware#3]
Manufacturers keep asking for them, maybe we should have them under version control. My only concern is that it could end up out of sync with the eagle file, which I think should be the source of truth. If that's the case, perhaps it'd be easier to put instructions in the README for how to make them. I'd love an automated build process that generates it, but that sounds like way more work than it's worth.

**Comment by williamcodes** [comment]
I can take a crack at this one.

**Comment by hrldcpr** [comment]
[This tutorial](https://learn.sparkfun.com/tutorials/using-eagle-board-layout/generating-gerbers) is good. You just clone [their repo](https://github.com/sparkfun/SparkFun_Eagle_Settings) and use `sfe-gerb274x.cam`

I usually avoid committing generated content, but meh whatever.
